### PR TITLE
added option for face detection in uploaded image

### PR DESCRIPTION
**Pull request by ayushanand308**
Please review the PR @mrsparkle-70

### CODE REVIEW

**Review by mrsparkle-70 — CHANGES_REQUESTED** [review]
Change the title of image.html from Document to something else .

**Comment by ayushanand308** [comment]
@mrsparkle-70 A humble request not to change the difficulty tag after submission because it took me effort to implement the feature.

**Comment by mrsparkle-70** [comment]
It is not the feature I asked for
I asked to upload a picture taken from *the live video* and store it

**Comment by ayushanand308** [comment]
@mrsparkle-70 That was mistake on my part. So can you elaborate on what you want so that I can implement it as a new feature?

**Pull request merged**
