### PR TITLE
Responsive UI created 

### LINKED ISSUE #56: [Enhancement] Adding Mobile Responsiveness
# Reason/Context

### Why we need this improvement?
In this current version of the page, the mobile version is broken as the UI basically breaks.

### How will this change help?
It will enhance the UI of the webpage, hence giving a better user-experience.

### What changes have to be introduced?
Some significant changes in the UI have to be made in order to make it mobile responsive.

### Will this be a breaking change?
No, it will not break the change.

## Related Screenshot : 
responsive

## I would like to work in this issue under JWOC 2023. Please assign me. Thanks. @mrsparkle-70

### PR DESCRIPTION
**Pull request by pooranjoyb**
# Description

## Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've made the enhancement both for light as well as dark modes
- [x] I ensured that the page remains responsive after the addition of the custom CSS

## Add relevant screenshot or video (if any)

[demo-emotionjs.webm](https://user-images.githubusercontent.com/90945182/221786838-e2d6c98f-b482-4a0b-aa49-5453144eee57.webm)

## Loved to work on this issue ❤️ Please merge this PR @mrsparkle-70

### CODE REVIEW

**Comment by mrsparkle-70** [comment]
Could you here recheck whether the prediction is working or not , after the
changes Made by you ?
I find them not working.
Anyways good CSS restructuring.

**Comment by pooranjoyb** [comment]
Yeah, sorry for that, a container height and width have to be passed along with html to make the faceapi.js work. 
While redesigning the Application I might have overwritten using custom CSS.
However I have found the fix, if you want me, I would create another issue to fix it. @mrsparkle-70

**Comment by mrsparkle-70** [comment]
Ok go ahead
The new issue will be assigned to you

**Comment by mrsparkle-70** [comment]
Create the issue 
Make the PR 
I will assign accordingly

**Comment by pooranjoyb** [comment]
Okay sure bhaiyaa @mrsparkle-70 ❤️

**Pull request merged**
